from __future__ import annotations

import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import requests

from .sandbox_runner import run_tests_in_sandbox

API_BASE = os.getenv("CODEBASE_AGENT_API", "http://localhost:8000")
SANDBOX_REQUIRED = os.getenv("SANDBOX_REQUIRED", "true").lower() in {"1", "true", "yes"}


@dataclass
class Task:
  id: int
  project_id: str
  type: str
  payload: dict[str, Any]


def _api_get(path: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
  resp = requests.get(f"{API_BASE}{path}", params=params, timeout=60)
  if resp.status_code >= 400:
    raise RuntimeError(resp.text)
  return resp.json()


def _api_post(path: str, payload: dict[str, Any]) -> dict[str, Any]:
  resp = requests.post(f"{API_BASE}{path}", json=payload, timeout=300)
  if resp.status_code >= 400:
    raise RuntimeError(resp.text)
  return resp.json()


def _next_task() -> Task | None:
  resp = requests.get(f"{API_BASE}/tasks/next", timeout=30)
  if resp.status_code == 404:
    return None
  if resp.status_code >= 400:
    raise RuntimeError(resp.text)
  data = resp.json().get("result", {})
  return Task(id=data["id"], project_id=data["project_id"], type=data["type"], payload=data.get("payload", {}))


def _complete_task(task_id: int, status: str, result: dict[str, Any]) -> None:
  requests.post(f"{API_BASE}/tasks/complete", json={"task_id": task_id, "status": status, "result": result}, timeout=60)


def _run_refactor_pipeline(task: Task) -> dict[str, Any]:
  repo_id = task.payload.get("repo_id", task.project_id)
  analysis = _api_post("/analysis/run", {"repo_id": repo_id, "commit_sha": "HEAD"})
  proposal = _api_post("/refactors/propose", {"analysis_id": analysis["analysis_id"], "scope": ["src/**"], "max_changes": 5})
  apply_res = _api_post("/refactors/apply", {"proposal_id": proposal["proposal_id"], "run_tests": False})

  repo_info = _api_get(f"/repos/{repo_id}")
  tests = run_tests_in_sandbox(repo_info["path"])

  if tests["status"] == "failed":
    return {"status": "failed", "reason": "tests_failed", "tests": tests, "analysis": analysis, "proposal": proposal, "apply": apply_res}

  if SANDBOX_REQUIRED and not tests.get("sandbox"):
    return {"status": "failed", "reason": "sandbox_required", "tests": tests}

  pr = _api_post("/github/pr", {
    "run_id": apply_res["run_id"],
    "repo_id": repo_id,
    "base": repo_info["branch"],
    "head_branch": f"codebase-agent/{proposal['proposal_id']}",
    "title": f"AI agent: {proposal['title']}",
    "body": "Generated by autonomous pipeline"
  })
  return {"status": "completed", "analysis": analysis, "proposal": proposal, "apply": apply_res, "pr": pr, "tests": tests}


def run_task(task: Task) -> dict[str, Any]:
  if task.type == "index_repo":
    return _api_post("/index/repo", {"repo_id": task.project_id})
  if task.type == "refactor_pipeline":
    return _run_refactor_pipeline(task)
  return {"status": "unknown task"}


def main() -> None:
  while True:
    task = _next_task()
    if not task:
      time.sleep(2)
      continue
    try:
      result = run_task(task)
      _complete_task(task.id, "completed", result)
    except Exception as exc:
      _complete_task(task.id, "failed", {"error": str(exc)})


if __name__ == "__main__":
  main()
