"use client"

import { useState } from "react"

type ImportResponse = {
  repo_id: string
  commit_sha: string
  status: string
}

type AnalysisResponse = {
  analysis_id: string
  status: string
}

type AnalysisResult = {
  status: string
  summary: string
  hotspots: Array<{ file: string; reason: string }>
  module_graph_url: string
}

type ProposalResponse = {
  proposal_id: string
  title: string
  risk: "low" | "medium" | "high"
  files: string[]
}

type ApplyResponse = {
  run_id: string
  status: string
}

type PrResponse = {
  pr_url: string
  status: "opened" | "skipped" | "failed"
}

export default function RunPanel() {
  const [repoUrl, setRepoUrl] = useState("https://github.com/org/repo")
  const [branch, setBranch] = useState("main")
  const [repoId, setRepoId] = useState("")
  const [commitSha, setCommitSha] = useState("")
  const [analysisId, setAnalysisId] = useState("")
  const [proposalId, setProposalId] = useState("")
  const [runId, setRunId] = useState("")
  const [headBranch, setHeadBranch] = useState("")
  const [status, setStatus] = useState("idle")
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null)
  const [proposal, setProposal] = useState<ProposalResponse | null>(null)
  const [prResult, setPrResult] = useState<PrResponse | null>(null)

  const apiBase = process.env.NEXT_PUBLIC_API_BASE ?? "http://localhost:8000"

  async function handleImport() {
    setStatus("importing repository")
    const res = await fetch(`${apiBase}/repos/import`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ repo_url: repoUrl, branch })
    })
    if (!res.ok) {
      setStatus(`import failed: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as ImportResponse
    setRepoId(data.repo_id)
    setCommitSha(data.commit_sha)
    setStatus(`repo imported: ${data.repo_id}`)
  }

  async function handleAnalysis() {
    if (!repoId) return
    setStatus("analysis running")
    const res = await fetch(`${apiBase}/analysis/run`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ repo_id: repoId, commit_sha: "HEAD" })
    })
    if (!res.ok) {
      setStatus(`analysis start failed: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as AnalysisResponse
    setAnalysisId(data.analysis_id)
    const detailRes = await fetch(`${apiBase}/analysis/${data.analysis_id}`)
    if (!detailRes.ok) {
      setStatus(`analysis fetch failed: ${await detailRes.text()}`)
      return
    }
    const detail = (await detailRes.json()) as AnalysisResult
    setAnalysis(detail)
    setStatus(`analysis completed: ${data.analysis_id}`)
  }

  async function handleProposal() {
    if (!analysisId) return
    setStatus("generating proposal")
    const res = await fetch(`${apiBase}/refactors/propose`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ analysis_id: analysisId, scope: ["src/**"], max_changes: 5 })
    })
    if (!res.ok) {
      setStatus(`proposal failed: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as ProposalResponse
    setProposalId(data.proposal_id)
    setHeadBranch(`codebase-agent/${data.proposal_id}`)
    setProposal(data)
    setStatus(`proposal created: ${data.proposal_id}`)
  }

  async function handleApply() {
    if (!proposalId) return
    setStatus("applying refactor")
    const res = await fetch(`${apiBase}/refactors/apply`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ proposal_id: proposalId, run_tests: true })
    })
    if (!res.ok) {
      setStatus(`apply failed: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as ApplyResponse
    setRunId(data.run_id)
    setStatus(`refactor applied: ${data.run_id}`)
  }

  async function handlePrDraft() {
    if (!runId || !repoId || !headBranch) return
    setStatus("creating pr draft")
    const res = await fetch(`${apiBase}/github/pr`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        run_id: runId,
        repo_id: repoId,
        base: branch,
        head_branch: headBranch,
        title: `AI agent: ${proposal?.title ?? "refactor proposal"}`,
        body: "Generated by Codebase Agent from MVP UI"
      })
    })
    if (!res.ok) {
      setStatus(`pr draft failed: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as PrResponse
    setPrResult(data)
    setStatus(`pr status: ${data.status}`)
  }

  return (
    <div className="card">
      <h2>MVP Runner</h2>
      <p>Run full flow: import, analysis, proposal, apply, and PR draft.</p>
      <div style={{ display: "grid", gap: 12 }}>
        <input className="input" value={repoUrl} onChange={(e) => setRepoUrl(e.target.value)} placeholder="Repository URL" />
        <input className="input" value={branch} onChange={(e) => setBranch(e.target.value)} placeholder="Branch" />
        <button className="button" onClick={handleImport}>Import Repository</button>
        <button className="button" onClick={handleAnalysis} disabled={!repoId}>Run Analysis</button>
        <button className="button" onClick={handleProposal} disabled={!analysisId}>Generate Refactor Proposal</button>
        <button className="button" onClick={handleApply} disabled={!proposalId}>Apply Refactor</button>
        <button className="button" onClick={handlePrDraft} disabled={!runId}>Create PR Draft</button>
      </div>
      <p><strong>Status:</strong> {status}</p>
      <p><strong>Repo ID:</strong> {repoId || "-"}</p>
      <p><strong>Commit SHA:</strong> {commitSha || "-"}</p>
      <p><strong>Analysis ID:</strong> {analysisId || "-"}</p>
      <p><strong>Proposal ID:</strong> {proposalId || "-"}</p>
      <p><strong>Run ID:</strong> {runId || "-"}</p>
      <p><strong>Head Branch:</strong> {headBranch || "-"}</p>
      {analysis && (
        <div className="panel">
          <h3>Architecture Summary</h3>
          <p>{analysis.summary}</p>
          <p><strong>Module graph:</strong> {analysis.module_graph_url}</p>
          <ul>
            {analysis.hotspots.map((hotspot) => (
              <li key={`${hotspot.file}-${hotspot.reason}`}>
                <code>{hotspot.file}</code> - {hotspot.reason}
              </li>
            ))}
          </ul>
        </div>
      )}
      {proposal && (
        <div className="panel">
          <h3>Proposal</h3>
          <p><strong>Title:</strong> {proposal.title}</p>
          <p><strong>Risk:</strong> {proposal.risk}</p>
          <ul>
            {proposal.files.map((file) => (
              <li key={file}><code>{file}</code></li>
            ))}
          </ul>
        </div>
      )}
      {prResult && (
        <div className="panel">
          <h3>PR Result</h3>
          <p><strong>Status:</strong> {prResult.status}</p>
          <p><strong>URL:</strong> {prResult.pr_url}</p>
        </div>
      )}
    </div>
  )
}
