"use client"

import { useState } from "react"

import { useI18n } from "./I18nProvider"

type ImportResponse = {
  repo_id: string
  commit_sha: string
  status: string
}

type AnalysisResponse = {
  analysis_id: string
  status: string
}

type AnalysisResult = {
  status: string
  summary: string
  hotspots: Array<{ file: string; reason: string }>
  module_graph_url: string
}

type ProposalResponse = {
  proposal_id: string
  title: string
  risk: "low" | "medium" | "high"
  files: string[]
}

type ApplyResponse = {
  run_id: string
  status: string
}

type PrResponse = {
  pr_url: string
  status: "opened" | "skipped" | "failed"
}

export default function RunPanel() {
  const { t } = useI18n()
  const [repoUrl, setRepoUrl] = useState("https://github.com/org/repo")
  const [branch, setBranch] = useState("main")
  const [repoId, setRepoId] = useState("")
  const [commitSha, setCommitSha] = useState("")
  const [analysisId, setAnalysisId] = useState("")
  const [proposalId, setProposalId] = useState("")
  const [runId, setRunId] = useState("")
  const [headBranch, setHeadBranch] = useState("")
  const [statusKey, setStatusKey] = useState("status.idle")
  const [statusDetail, setStatusDetail] = useState("")
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null)
  const [proposal, setProposal] = useState<ProposalResponse | null>(null)
  const [prResult, setPrResult] = useState<PrResponse | null>(null)

  const apiBase = process.env.NEXT_PUBLIC_API_BASE ?? "http://localhost:8000"

  async function handleImport() {
    setStatusKey("status.importing")
    setStatusDetail("")
    const res = await fetch(`${apiBase}/repos/import`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ repo_url: repoUrl, branch })
    })
    if (!res.ok) {
      setStatusKey("status.importing")
      setStatusDetail(`error: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as ImportResponse
    setRepoId(data.repo_id)
    setCommitSha(data.commit_sha)
    setStatusKey("status.importing")
    setStatusDetail(data.repo_id)
  }

  async function handleAnalysis() {
    if (!repoId) return
    setStatusKey("status.analysisRunning")
    setStatusDetail("")
    const res = await fetch(`${apiBase}/analysis/run`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ repo_id: repoId, commit_sha: "HEAD" })
    })
    if (!res.ok) {
      setStatusDetail(`error: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as AnalysisResponse
    setAnalysisId(data.analysis_id)
    const detailRes = await fetch(`${apiBase}/analysis/${data.analysis_id}`)
    if (!detailRes.ok) {
      setStatusDetail(`error: ${await detailRes.text()}`)
      return
    }
    const detail = (await detailRes.json()) as AnalysisResult
    setAnalysis(detail)
    setStatusKey("status.analysisDone")
    setStatusDetail(data.analysis_id)
  }

  async function handleProposal() {
    if (!analysisId) return
    setStatusKey("status.proposalGenerating")
    setStatusDetail("")
    const res = await fetch(`${apiBase}/refactors/propose`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ analysis_id: analysisId, scope: ["src/**"], max_changes: 5 })
    })
    if (!res.ok) {
      setStatusDetail(`error: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as ProposalResponse
    setProposalId(data.proposal_id)
    setHeadBranch(`codebase-agent/${data.proposal_id}`)
    setProposal(data)
    setStatusKey("status.proposalDone")
    setStatusDetail(data.proposal_id)
  }

  async function handleApply() {
    if (!proposalId) return
    setStatusKey("status.applyRunning")
    setStatusDetail("")
    const res = await fetch(`${apiBase}/refactors/apply`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ proposal_id: proposalId, run_tests: true })
    })
    if (!res.ok) {
      setStatusDetail(`error: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as ApplyResponse
    setRunId(data.run_id)
    setStatusKey("status.applyDone")
    setStatusDetail(data.run_id)
  }

  async function handlePrDraft() {
    if (!runId || !repoId || !headBranch) return
    setStatusKey("status.prRunning")
    setStatusDetail("")
    const res = await fetch(`${apiBase}/github/pr`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        run_id: runId,
        repo_id: repoId,
        base: branch,
        head_branch: headBranch,
        title: `AI agent: ${proposal?.title ?? "refactor proposal"}`,
        body: "Generated by Codebase Agent from MVP UI"
      })
    })
    if (!res.ok) {
      setStatusDetail(`error: ${await res.text()}`)
      return
    }
    const data = (await res.json()) as PrResponse
    setPrResult(data)
    setStatusKey("status.prDone")
    setStatusDetail(data.status)
  }

  return (
    <div className="card">
      <h2>{t("runner.title")}</h2>
      <p>{t("runner.subtitle")}</p>
      <div style={{ display: "grid", gap: 12 }}>
        <input className="input" value={repoUrl} onChange={(e) => setRepoUrl(e.target.value)} placeholder={t("runner.repoUrl")} />
        <input className="input" value={branch} onChange={(e) => setBranch(e.target.value)} placeholder={t("runner.branch")} />
        <button className="button" onClick={handleImport}>{t("runner.import")}</button>
        <button className="button" onClick={handleAnalysis} disabled={!repoId}>{t("runner.analysis")}</button>
        <button className="button" onClick={handleProposal} disabled={!analysisId}>{t("runner.propose")}</button>
        <button className="button" onClick={handleApply} disabled={!proposalId}>{t("runner.apply")}</button>
        <button className="button" onClick={handlePrDraft} disabled={!runId}>{t("runner.pr")}</button>
      </div>
      <p><strong>{t("runner.status")}:</strong> {t(statusKey)}{statusDetail ? `: ${statusDetail}` : ""}</p>
      <p><strong>{t("runner.repoId")}:</strong> {repoId || "-"}</p>
      <p><strong>{t("runner.commit")}:</strong> {commitSha || "-"}</p>
      <p><strong>{t("runner.analysisId")}:</strong> {analysisId || "-"}</p>
      <p><strong>{t("runner.proposalId")}:</strong> {proposalId || "-"}</p>
      <p><strong>{t("runner.runId")}:</strong> {runId || "-"}</p>
      <p><strong>{t("runner.headBranch")}:</strong> {headBranch || "-"}</p>
      {analysis && (
        <div className="panel">
          <h3>{t("runner.archSummary")}</h3>
          <p>{analysis.summary}</p>
          <p><strong>{t("runner.moduleGraph")}:</strong> {analysis.module_graph_url}</p>
          <ul>
            {analysis.hotspots.map((hotspot) => (
              <li key={`${hotspot.file}-${hotspot.reason}`}>
                <code>{hotspot.file}</code> - {hotspot.reason}
              </li>
            ))}
          </ul>
        </div>
      )}
      {proposal && (
        <div className="panel">
          <h3>{t("runner.proposalTitle")}</h3>
          <p><strong>{t("runner.titleLabel")}:</strong> {proposal.title}</p>
          <p><strong>{t("runner.risk")}:</strong> {proposal.risk}</p>
          <ul>
            {proposal.files.map((file) => (
              <li key={file}><code>{file}</code></li>
            ))}
          </ul>
        </div>
      )}
      {prResult && (
        <div className="panel">
          <h3>{t("runner.prResult")}</h3>
          <p><strong>{t("runner.status")}:</strong> {prResult.status}</p>
          <p><strong>{t("runner.url")}:</strong> {prResult.pr_url}</p>
        </div>
      )}
    </div>
  )
}
