from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


class RepoImportRequest(BaseModel):
    repo_url: str
    branch: str = "main"


class RepoImportResponse(BaseModel):
    repo_id: str
    commit_sha: str
    status: Literal["queued", "running", "completed", "failed"] = "queued"


class AnalysisRunRequest(BaseModel):
    repo_id: str
    commit_sha: str = "HEAD"


class AnalysisRunResponse(BaseModel):
    analysis_id: str
    status: Literal["queued", "running", "completed", "failed"] = "running"


class Hotspot(BaseModel):
    file: str
    reason: str


class AnalysisResultResponse(BaseModel):
    status: Literal["queued", "running", "completed", "failed"]
    summary: str
    hotspots: list[Hotspot] = Field(default_factory=list)
    module_graph_url: str


class RefactorProposalRequest(BaseModel):
    analysis_id: str
    scope: list[str] = Field(default_factory=lambda: ["src/**"])
    max_changes: int = 5


class RefactorProposalResponse(BaseModel):
    proposal_id: str
    title: str
    risk: Literal["low", "medium", "high"]
    files: list[str]


class RefactorApplyRequest(BaseModel):
    proposal_id: str
    run_tests: bool = True


class RefactorApplyResponse(BaseModel):
    run_id: str
    status: Literal["queued", "running", "completed", "failed"] = "running"


class GithubPrRequest(BaseModel):
    run_id: str
    repo_id: str
    base: str = "main"
    head_branch: str
    title: str = "AI agent: refactor proposal"
    body: str = "Automated draft PR generated by Codebase Agent."


class GithubPrResponse(BaseModel):
    pr_url: str
    status: Literal["opened", "skipped", "failed"] = "opened"


class IndexRepoRequest(BaseModel):
    repo_id: str


class IndexRepoResponse(BaseModel):
    status: Literal["completed", "failed"]
    chunks: int = 0


class ChatRequest(BaseModel):
    project_id: str
    message: str
    conversation_id: int | None = None


class ChatResponse(BaseModel):
    conversation_id: int
    answer: str


class FeedbackRequest(BaseModel):
    project_id: str
    rating: Literal["up", "down"]
    run_id: str | None = None
    reason: str | None = None


class FeedbackResponse(BaseModel):
    status: Literal["ok"] = "ok"


class TaskEnqueueRequest(BaseModel):
    project_id: str
    type: str
    payload: dict[str, Any] = Field(default_factory=dict)


class TaskEnqueueResponse(BaseModel):
    task_id: int
    status: Literal["queued"] = "queued"


class TaskStatusResponse(BaseModel):
    task_id: int
    status: str
    result: dict[str, Any] | None = None
